### ISSUE TITLE
latest update breaks everything

### ISSUE THREAD

**Issue by rami-dabain** [revel/cmd#150]
Fresh revel install on a fresh system:
revel package doesnt produce anything usefull
missing importPath in run.sh script, if fixed manually by adding the correct import, the executable just dies without any warnings/errors or anything.

**Comment by notzippy** [comment]
There was an issue in the template which was corrected. This should be resolved now - if not feel free to reopen

**Comment by rami-dabain** [comment]
Yup still broken.
I think the issue is only when you have an older project and you update revel

INFO  14:49:38 command_config.go:152: Returned import path                     buildpath=/go  path=okitoo/hackers_reloaded/main
INFO  14:49:38   file.go:346: Seeking app package                      app=okitoo/hackers_reloaded/main 
INFO  14:49:38   file.go:354: Seeking remote package                   using=okitoo/hackers_reloaded/main remote=github.com/revel/revel 
INFO  14:49:38   file.go:357: Resolved called Seeking remote package   using=okitoo/hackers_reloaded/main remote=github.com/revel/revel 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6331d5]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0x7ffc4b99afc2, 0x1c, 0x8dc2c6, 0x16, 0x0, 0x0, 0x0, 0x815700, 0xc000095e60, 0xc00016dc68, ...)
        /go/src/github.com/revel/cmd/utils/file.go:358 +0x4f5
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc000140000, 0x8dae7b, 0x14)
        /go/src/github.com/revel/cmd/model/command_config.go:301 +0xc0
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc000140000, 0x24, 0x3)
        /go/src/github.com/revel/cmd/model/command_config.go:154 +0x68e
main.main()
        /go/src/github.com/revel/cmd/revel/revel.go:94 +0x161
